# -*- coding: utf-8 -*-
"""semantic_error_deepseek_qwen_mistral_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIR5PrysAT89cQVmnlyvGULV8qBkv6ZC
"""

# pip install -r requirements.txt

# !python run.py --mode run --models qwen-2.5-7b --trials 10

# !python run.py --mode run --models mistral-7b --trials 10

# import importlib
# import models
# importlib.reload(models)

# !python run.py --mode run --models deepseek-r1-7b --trials 5

# !pip install -q huggingface_hub

# from huggingface_hub import login
# login(token="....")

# !python run.py --mode run --models llama-3.1-8b --trials 10

